### ISSUE TITLE
Please issue new version to support Jekyll 4.0.0

### ISSUE THREAD

**Issue by Balancingrock** [ashmaroli/jekyll-data#33]
My theme (Classic-Jekyll-Theme) depends on jekyll-data. In order to support Jekyll 4.0 a new version of jekyll-data is necessary.
I know that HEAD should have this issue resolved, but until the gem is published in a new release my users cannot upgrade to Jekyll 4.0

**Comment by ashmaroli** [comment]
The reasons why I didn't ship a release are:
  - Jekyll 4.0 has added support for loading a `_config.yml` from a theme-gem when available.
  - Jekyll 4.1 **may add** support for loading data files from a theme-gem as well.

Thereby leaving this plugin redundant once Jekyll 4.1 ships.

However, I understand your predicament and shall cut a new version *soon*..

**Comment by Balancingrock** [comment]
Thank you, appreciate it very much.

**Comment by ashmaroli** [comment]
[`v1.1.0`](https://rubygems.org/gems/jekyll-data/versions/1.1.0) has been released.
